"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const removeBookmark_1 = require("./../controller/Memory/removeBookmark");
const UnLikeMemory_1 = require("./../controller/Memory/UnLikeMemory");
const LikeMemory_1 = require("./../controller/Memory/LikeMemory");
const GetPrivateMemories_1 = require("./../controller/Memory/GetPrivateMemories");
const auth_1 = require("./../controller/Authentication/auth");
const express_1 = require("express");
const UpdateMemory_1 = require("./../controller/Memory/UpdateMemory");
const GetMemory_1 = require("./../controller/Memory/GetMemory");
const CreateMemory_1 = require("./../controller/Memory/CreateMemory");
const GetMemories_1 = require("../controller/Memory/GetMemories");
const DeleteMemory_1 = require("../controller/Memory/DeleteMemory");
const GetMemoryByTags_1 = require("../controller/Memory/GetMemoryByTags");
const SearchMemory_1 = require("../controller/Memory/SearchMemory");
const bookmark_1 = require("../controller/Memory/bookmark");
const memoryRoutes = (0, express_1.Router)();
memoryRoutes.route(`/memories`).get(auth_1.protect, GetMemories_1.getAllMemories);
memoryRoutes.route(`/private-memories`).get(auth_1.protect, GetPrivateMemories_1.getAllPrivateMemories);
memoryRoutes.get(`/memories/:id`, auth_1.protect, GetMemory_1.getMemory);
memoryRoutes.get(`/search-memories`, auth_1.protect, SearchMemory_1.searchMemory);
memoryRoutes.get(`/memories-by-tag`, GetMemoryByTags_1.getMemoryByTag);
memoryRoutes.patch(`/update-memory/:id`, UpdateMemory_1.updateMemory);
memoryRoutes.post(`/create-memory`, auth_1.protect, CreateMemory_1.createMemory);
memoryRoutes.post(`/like-memory`, auth_1.protect, LikeMemory_1.likeMemory);
memoryRoutes.post(`/un-like-memory`, auth_1.protect, UnLikeMemory_1.unLikeMemory);
memoryRoutes.post(`/addbookmark-memory`, auth_1.protect, bookmark_1.addBookmark);
memoryRoutes.post(`/removeBookmark-memory`, auth_1.protect, removeBookmark_1.removeBookmark);
memoryRoutes.delete(`/delete-memory/:id`, DeleteMemory_1.deleteMemory);
exports.default = memoryRoutes;
